### ISSUE TITLE
Do not add X-Smartstack-Destination/X-Smartstack-Source if already present in the request

### ISSUE THREAD

**Issue by ArnaudBrousseau** [Yelp/synapse-tools#23]
For services with `proxied_through` directive, we're adding `X-Smartstack-Destination` (https://github.com/Yelp/synapse-tools/blob/master/src/synapse_tools/configure_synapse.py#L217) and `X-Smartstack-Source` (https://github.com/Yelp/synapse-tools/blob/master/src/synapse_tools/configure_synapse.py#L372) to the request without checking if these headers are there first. This causes HAProxy to sometimes produce requests containing 2 lines with the same header name, e.g.:
```
GET /bar HTTP/1.0
Host: foo
X-Smartstack-Source: src
X-Smartstack-Destination: dst
X-Smartstack-Destination: dst
```
Head scratching and painful debugging ensue.

Let's make these `reqadd` conditional: only add headers if they're currently absent from the request. If they're already provided, leave them as-is.

**Comment by kaisen** [comment]
Done in #67!
