### ISSUE TITLE
Warnings from haproxy about regex use without 'mode http'

### ISSUE THREAD

**Issue by matfra** [Yelp/synapse-tools#54]
We should ensure we explicitely specify mode http in the proxy configurations whenever it's necessary to avoid these messages:

`[WARNING] 105/075129 (82780) : config : client regular expressions will be ignored for backend 'foobar.main' (needs 'mode http').`

**Comment by matfra** [comment]
This is a followup from the discussion with @avadhutp in #53

**Comment by danielpops** [comment]
Closing after 4 years of inactivity
